# Copyright (c) 2026, Imogi and contributors
"""Frappe role → DocType permissions aligned with IMOGI matrix personas.

Matrix roles (feature_registry): Owner, Manager, Inventory, Purchasing, Finance, …
Frappe roles (User Has Role): IMOGI Owner, IMOGI Inventory, IMOGI Purchasing, …
"""

from __future__ import annotations

# role_name → list of (doctype, perm_dict)
IMOGI_ROLE_PERMISSIONS: dict[str, list[tuple[str, dict]]] = {
	"IMOGI Owner": [
		("IMOGI POS Settings", {"read": 1, "write": 1}),
		("IMOGI Area Manager Assignment", {"read": 1, "write": 1, "create": 1, "delete": 1}),
		("Riwayat Order", {"read": 1, "report": 1}),
		("POS Invoice", {"read": 1}),
		("Sales Invoice", {"read": 1}),
		("Purchase Invoice", {"read": 1}),
		("Payment Entry", {"read": 1}),
		("Journal Entry", {"read": 1}),
		("Purchase Order", {"read": 1}),
		("Purchase Receipt", {"read": 1}),
		("Material Request", {"read": 1}),
		("Stock Entry", {"read": 1, "write": 1, "create": 1, "submit": 1}),
		("Stock Settings", {"read": 1}),
		("Item", {"read": 1}),
		("IMOGI POS Gateway Payment", {"read": 1, "write": 1}),
		("Page", {"read": 1}),
		("Report", {"read": 1}),
		("Company", {"read": 1}),
		("IMOGI Branch", {"read": 1, "write": 1, "create": 1}),
		("POS Profile", {"read": 1, "write": 1, "create": 1}),
		("User Permission", {"read": 1, "write": 1, "create": 1}),
		("Warehouse", {"read": 1}),
	],
	"IMOGI Finance": [
		("IMOGI POS Settings", {"read": 1}),
		("Payment Entry", {"read": 1, "write": 1, "create": 1, "submit": 1, "cancel": 1}),
		("Purchase Invoice", {"read": 1, "write": 1, "create": 1, "submit": 1, "cancel": 1}),
		("Sales Invoice", {"read": 1, "write": 1, "create": 1, "submit": 1, "cancel": 1}),
		("Journal Entry", {"read": 1, "write": 1, "create": 1, "submit": 1, "cancel": 1}),
		("Account", {"read": 1}),
		("Customer", {"read": 1, "write": 1, "create": 1}),
		("Supplier", {"read": 1}),
		("POS Invoice", {"read": 1}),
		("Riwayat Order", {"read": 1, "report": 1}),
		("Company", {"read": 1}),
		("IMOGI Branch", {"read": 1}),
		("IMOGI POS Royalty Accrual", {"read": 1, "write": 1, "create": 1}),
		("Page", {"read": 1}),
		("Report", {"read": 1}),
	],
	"IMOGI Inventory": [
		("IMOGI POS Settings", {"read": 1}),
		("Item", {"read": 1, "write": 1, "create": 1}),
		("Item Group", {"read": 1, "write": 1}),
		("Warehouse", {"read": 1}),
		("Stock Entry", {"read": 1, "write": 1, "create": 1, "submit": 1, "cancel": 1}),
		("Stock Reconciliation", {"read": 1, "write": 1, "create": 1, "submit": 1, "cancel": 1}),
		("Batch", {"read": 1, "write": 1, "create": 1}),
		("BOM", {"read": 1}),
		("UOM", {"read": 1}),
		("Company", {"read": 1}),
		("IMOGI Branch", {"read": 1}),
		("POS Profile", {"read": 1}),
		("Page", {"read": 1}),
		("Report", {"read": 1}),
	],
	"IMOGI Purchasing": [
		("IMOGI POS Settings", {"read": 1}),
		("Supplier", {"read": 1, "write": 1, "create": 1}),
		("Material Request", {"read": 1, "write": 1, "create": 1, "submit": 1, "cancel": 1}),
		("Purchase Order", {"read": 1, "write": 1, "create": 1, "submit": 1, "cancel": 1}),
		("Purchase Receipt", {"read": 1, "write": 1, "create": 1, "submit": 1, "cancel": 1}),
		("Item", {"read": 1}),
		("Warehouse", {"read": 1}),
		("Company", {"read": 1}),
		("IMOGI Branch", {"read": 1}),
		("Page", {"read": 1}),
		("Report", {"read": 1}),
	],
	"IMOGI Manager": [
		("IMOGI POS Settings", {"read": 1}),
		("Riwayat Order", {"read": 1, "report": 1}),
		("Item", {"read": 1, "write": 1, "create": 1}),
		("Item Group", {"read": 1, "write": 1, "create": 1}),
		("Item Price", {"read": 1, "write": 1, "create": 1}),
		("BOM", {"read": 1, "write": 1, "create": 1}),
		("Page", {"read": 1}),
		("Report", {"read": 1}),
		("Company", {"read": 1}),
		("IMOGI Branch", {"read": 1}),
		("Warehouse", {"read": 1}),
		("POS Profile", {"read": 1}),
		("IMOGI POS Combo Package", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Loyalty Member", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Voucher", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Loyalty Tier", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Promo Rule", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Loyalty Transaction", {"read": 1}),
	],
	"IMOGI Area Manager": [
		("IMOGI POS Settings", {"read": 1}),
		("IMOGI Area Manager Assignment", {"read": 1}),
		("Riwayat Order", {"read": 1, "report": 1}),
		("Item", {"read": 1, "write": 1, "create": 1}),
		("Item Group", {"read": 1, "write": 1, "create": 1}),
		("Item Price", {"read": 1, "write": 1, "create": 1}),
		("BOM", {"read": 1, "write": 1, "create": 1}),
		("Page", {"read": 1}),
		("Report", {"read": 1}),
		("Company", {"read": 1}),
		("IMOGI Branch", {"read": 1, "write": 1}),
		("Warehouse", {"read": 1}),
		("POS Profile", {"read": 1}),
		("Material Request", {"read": 1, "write": 1, "create": 1, "submit": 1}),
		("Purchase Order", {"read": 1, "write": 1, "create": 1, "submit": 1}),
		("Purchase Receipt", {"read": 1, "write": 1, "create": 1, "submit": 1}),
		("Stock Entry", {"read": 1, "write": 1, "create": 1, "submit": 1}),
		("Supplier", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Combo Package", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Loyalty Member", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Voucher", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Loyalty Tier", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Promo Rule", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Loyalty Transaction", {"read": 1}),
	],
	"IMOGI Waiter": [
		("Riwayat Order", {"read": 1, "write": 1, "create": 1, "submit": 1}),
		("IMOGI Restaurant Table", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Table Reservation", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Waiting List", {"read": 1, "write": 1, "create": 1}),
		("Customer", {"read": 1, "create": 1}),
		("Contact", {"read": 1, "create": 1}),
		("Page", {"read": 1}),
		("POS Profile", {"read": 1}),
		("Mode of Payment", {"read": 1}),
		("Company", {"read": 1}),
		("IMOGI Branch", {"read": 1}),
		("Warehouse", {"read": 1}),
	],
	"IMOGI Supervisor": [
		("Riwayat Order", {"read": 1, "write": 1, "create": 1, "submit": 1, "cancel": 1}),
		("IMOGI POS Approval Request", {"read": 1, "write": 1, "create": 1}),
		("IMOGI Restaurant Table", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Table Reservation", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Waiting List", {"read": 1, "write": 1, "create": 1}),
		("POS Invoice", {"read": 1}),
		("Purchase Order", {"read": 1}),
		("Stock Entry", {"read": 1}),
		("Customer", {"read": 1, "create": 1}),
		("Page", {"read": 1}),
		("POS Profile", {"read": 1}),
		("Mode of Payment", {"read": 1}),
		("Company", {"read": 1}),
		("IMOGI Branch", {"read": 1}),
	],
	"IMOGI Chef": [
		("IMOGI Kitchen Order", {"read": 1, "write": 1, "create": 1, "submit": 1}),
		("IMOGI Kitchen Station", {"read": 1}),
		("Riwayat Order", {"read": 1}),
		("BOM", {"read": 1, "write": 1, "create": 1}),
		("Item", {"read": 1}),
		("Page", {"read": 1}),
	],
	"IMOGI Cashier": [
		("Riwayat Order", {"read": 1, "write": 1, "create": 1, "submit": 1, "cancel": 1}),
		("IMOGI Restaurant Table", {"read": 1, "write": 1}),
		("IMOGI POS Table Reservation", {"read": 1}),
		("IMOGI POS Waiting List", {"read": 1}),
		("IMOGI POS Shift Opening", {"read": 1, "write": 1, "create": 1, "submit": 1}),
		("IMOGI POS Shift Closing", {"read": 1, "write": 1, "create": 1, "submit": 1}),
		("POS Invoice", {"read": 1}),
		("POS Opening Entry", {"read": 1, "write": 1, "create": 1, "submit": 1}),
		("POS Closing Entry", {"read": 1, "write": 1, "create": 1, "submit": 1}),
		("Customer", {"read": 1, "create": 1}),
		("Contact", {"read": 1, "create": 1}),
		("Page", {"read": 1}),
		("POS Profile", {"read": 1}),
		("Mode of Payment", {"read": 1}),
		("Company", {"read": 1}),
		("IMOGI Branch", {"read": 1}),
		("Warehouse", {"read": 1}),
		("IMOGI POS Loyalty Member", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Voucher", {"read": 1}),
		("IMOGI POS Loyalty Transaction", {"read": 1}),
		("IMOGI POS Promo Rule", {"read": 1}),
		("IMOGI POS Loyalty Tier", {"read": 1}),
		("IMOGI POS Offline Checkout", {"read": 1, "write": 1, "create": 1}),
	],
	"IMOGI Kitchen Staff": [
		("IMOGI Kitchen Order", {"read": 1, "write": 1, "create": 1, "submit": 1}),
		("Riwayat Order", {"read": 1, "write": 1}),
	],
	"IMOGI Fulfillment Staff": [
		("IMOGI Fulfillment Task", {"read": 1, "write": 1, "create": 1, "submit": 1}),
		("Riwayat Order", {"read": 1, "write": 1}),
	],
	"IMOGI Rider": [
		("IMOGI Delivery Task", {"read": 1, "write": 1, "submit": 1}),
		("Riwayat Order", {"read": 1}),
	],
	"IMOGI Auditor": [
		("Riwayat Order", {"read": 1, "report": 1}),
		("POS Invoice", {"read": 1}),
		("Version", {"read": 1}),
		("Activity Log", {"read": 1}),
		("Report", {"read": 1}),
		("Page", {"read": 1}),
		("Company", {"read": 1}),
		("IMOGI Branch", {"read": 1}),
	],
	"Sales Manager": [
		("IMOGI Branch", {"read": 1, "write": 1, "create": 1}),
		("Stock Entry", {"read": 1, "write": 1, "create": 1, "submit": 1}),
		("IMOGI POS Voucher", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Loyalty Member", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Loyalty Transaction", {"read": 1}),
		("IMOGI POS Promo Rule", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Loyalty Tier", {"read": 1, "write": 1, "create": 1}),
		("IMOGI POS Royalty Accrual", {"read": 1, "write": 1, "create": 1}),
		("Journal Entry", {"read": 1}),
	],
}

IMOGI_DESK_ROLES = tuple(IMOGI_ROLE_PERMISSIONS.keys())

# feature_id → (doctype, permission_type) for API / data access guards
FEATURE_DOCTYPE_ACCESS: dict[str, tuple[str, str]] = {
	"menu": ("Item", "read"),
	"menu_category": ("Item Group", "read"),
	"modifier": ("Item", "read"),
	"add_on": ("Item", "read"),
	"order_history": ("Riwayat Order", "read"),
	"order_management": ("Riwayat Order", "write"),
	"pos_order": ("Riwayat Order", "write"),
	"raw_material": ("Item", "read"),
	"stock_raw": ("Item", "read"),
	"waste_management": ("Stock Entry", "read"),
	"stock_opname": ("Stock Reconciliation", "read"),
	"stock_adjustment": ("Stock Entry", "write"),
	"batch_tracking": ("Batch", "read"),
	"supplier": ("Supplier", "read"),
	"purchase_request": ("Material Request", "read"),
	"purchase_order": ("Purchase Order", "read"),
	"goods_receiving": ("Purchase Receipt", "read"),
	"cash_bank": ("Payment Entry", "read"),
	"supplier_payable": ("Purchase Invoice", "read"),
	"customer_receivable": ("Sales Invoice", "read"),
	"accounting_integration": ("Sales Invoice", "read"),
	"recipe_management": ("BOM", "read"),
	"qris": ("IMOGI POS Gateway Payment", "read"),
	"central_purchasing": ("Material Request", "write"),
	"central_inventory": ("IMOGI Branch", "read"),
	"sales_report": ("Riwayat Order", "report"),
	"profit_loss": ("Report", "read"),
	"cash_flow": ("Report", "read"),
	"tax_report": ("Report", "read"),
	"audit_log": ("Version", "read"),
	"login_history": ("Activity Log", "read"),
}

# Report name → Frappe roles that may run the report
INTEGRATION_REPORT_ROLES: dict[str, tuple[str, ...]] = {
	"Stock Ledger": (
		"IMOGI Inventory",
		"IMOGI Manager",
		"IMOGI Area Manager",
		"IMOGI Owner",
		"IMOGI Finance",
	),
	"Profit and Loss Statement": ("IMOGI Finance", "IMOGI Owner", "IMOGI Area Manager"),
	"Cash Flow": ("IMOGI Finance", "IMOGI Owner", "IMOGI Area Manager"),
	"Sales Register": ("IMOGI Finance", "IMOGI Owner"),
}


def get_imogi_role_permissions() -> dict[str, list[tuple[str, dict]]]:
	return IMOGI_ROLE_PERMISSIONS
